### PR TITLE
fix modal

### LINKED ISSUE #190: Modal component behind other components
The Modal component is behind the Page View and Tab Bar components

I believe that the ideal is the modal to be apparent in any situation

Capturar
Capturar2

### PR DESCRIPTION
**Pull request by gabrielpenhazup**
Closes #190

What I did
I made the modal stand in front of all the components

How I did it
adding a larger z-index to the component

How to verify it
Was tested using an react poc

Description for the changelog

### CODE REVIEW

**Comment by tayronemachadozup** [comment]
Gabriel run `yarn test -u` command to correct the failing snapshot test and follows the description patterns of a pr.

File: packages/beagle-react/src/components/Modal/styled.ts [hunk 1]
```diff
@@ -8,6 +8,7 @@ export const StyledModal = styled.div`
   left: 0;
   bottom: 0;
   right: 0;
+  z-index: 1;
```
Comment (arthurbleilzup) [inline packages/beagle-react/src/components/Modal/styled.ts:11]: I was wondering about this change and trying to think if there was a scenario where `z-index: 1` wouldn't be effective... well, beyond the Beagle elements it will not impact, only `BeagleModal` uses that behavior. 

On other hand, the developers that use Beagle can develop components that overlap this change, but there are more than one solution for that, that are the users implementing their features differently or overriding the style of `BeagleModal`, so I believe this is a good solution.

Ps. Sorry for the long text, just leaving my thoughts here, as reflection for next features...

**Review by arthurbleilzup — CHANGES_REQUESTED** [review]
Please run the command that @tayronearaujo mentioned on your machine, to update your tests snapshots and then commit it again to have this PR approved

**Review by arthurbleilzup — APPROVED** [review]

**Review by Tiagoperes — APPROVED** [review]
