### PR TITLE
fix script init

### LINKED ISSUE #191: beagle init not working in fresh project
Beagle React version:

## Steps To Reproduce

1. start a project from scratch by creating a new directory named `project`
2. `cd project`
3.  `yarn init`: use all default options (enter)
4. `yarn add react`
5. `yarn add @zup-it/beagle-react`
6. `yarn beagle init`

## The current behavior
It fails to execute saying the directory `src` doesn't exist. In this case, the script should create the directory `src`.

If I create the directory by myself, there's another problem. It prompts me with the message:
`Do you want to replace "app.tsx" content with the Beagle configuration (y or n)?`

I don't have any file in my project, why is it asking me if I want to replace anything? The script should only ask this if `app.tsx` exists in the project.

Furthermore, the file created has an uppercase "A", i.e. it's named `App.tsx`. This is a problem, the naming convention generally used with javascript would name it `app.tsx`, with a lowercase "a".

## The expected behavior
I expected the script to run, without errors and without questions. I also expected "App.tsx" to be named "app.tsx", in lowercase letters.

### PR DESCRIPTION
**Pull request by jamessonpenhazup**
**- What I did**
I made the necessary corrections for the script to work on all projects, even on a totally default project with no folder created. I also changed the name of the App.tsx file to app.tsx. Closes #191
**- How I did it**
If there is no folder, the script generates the src and the beagle
**- How to verify it**
1. start a project from scratch by creating a new directory named project
2. cd project
3. yarn init: use all default options (enter)
4. yarn add react
5. yarn add @zup-it/beagle-react
6. yarn beagle init
**- Description for the changelog**

### CODE REVIEW

File: packages/beagle-react/cli/init/index.js [hunk 1]
```diff
@@ -1,12 +1,15 @@
...
-const dir = 'src/beagle'
+const dir = 'src'
 const fileOptions = { encoding: 'utf8' }
 
 if (!fs.existsSync(dir)) {
   fs.mkdirSync(dir)
 }
+if (!fs.existsSync(dir + '/beagle/')) {
+  fs.mkdirSync(dir + '/beagle/')
+}
```
Comment (Tiagoperes) [inline packages/beagle-react/cli/init/index.js:12]: You don't need to create multiple ifs here, you only need the following line of code:

```typescript
fs.mkdirSync(dir, { recursive: true })
```

The line above does all of the following:
- it checks if the directory already exists and does nothing in case it exists
- creates any directory in the path, recursively. So, if `/src` doesn't exist, it will create it.

**Review by Tiagoperes — CHANGES_REQUESTED** [review]
An observation: **no need to change anything**, it's just a tip for the next time: callbacks are ugly, instead of using the module `fs`, you could use `fs/promises` and write your code with async/await.

File: packages/beagle-react/cli/init/index.js [hunk 2]
```diff
@@ -19,15 +22,23 @@ if (!fs.existsSync(dir)) {
...
+    })
+  }
+  else {
+    rl.question('Do you want to replace "app.tsx" content with the Beagle configuration (y or n)?', (answer) => {
+      if (`${answer}` === 'y') {
+        fs.writeFile('src/app.tsx', appContent, function (err) {
+          if (err) throw err
+          process.exit()
+        })
+      }
```
Comment (arthurbleilzup) [inline packages/beagle-react/cli/init/index.js:38]: Using the tips that @Tiagoperes gave to you, about `fs/promises`, you can also abstract those `fs.writeFile` into a method that returns a `Promise` and handle those `throw`, because they are currently uncaught.

```suggestion
async function createAppTsx(path: string, content: string): Promise<void> {
  try {
    await writeFile(`${path}/app.tsx`, content)
  } catch (error) {
    console.error(error)
    process.exit()
  }
}

// using it
// { ... }
if (`${answer}` === 'y') {
    await createAppTsx('src', appContent)        
}
process.exit()
```

Comment (arthurbleilzup) [reply packages/beagle-react/cli/init/index.js:38]: PS: do not commit this suggestion... made it a suggestion to be more easy to visualize

**Review by arthurbleilzup — CHANGES_REQUESTED** [review]

File: packages/beagle-react/cli/init/index.js [hunk 3]
```diff
@@ -1,11 +1,13 @@
 #!/usr/bin/env node
 const fs = require('fs')
 const fsPromises = fs.promises
-const dir = 'src/beagle'
+const dir = 'src'
 const fileOptions = { encoding: 'utf8' }
 
-if (!fs.existsSync(dir)) {
-  fs.mkdirSync(dir)
+fs.mkdirSync(dir, { recursive: true })
```
Comment (Tiagoperes) [inline packages/beagle-react/cli/init/index.js:7]: I don't think you understood it correctly.

Please, call mkdirSync only once!

```typescript
fs.mkdirSync(`${dir}/beagle`, { recursive: true })
```

after doing this, you can be sure `src/beagle` exists, no matter if `/src` exists or not (the directory has been created recursively).

The lines 9 to 11 don't need to exist.

**Review by Tiagoperes — CHANGES_REQUESTED** [review]
I just noticed you do import `fsPromises`. You're using both promises and callbacks to do the same thing. This is very confusing. Please update your code to use only fsPromises.

Since you're at it, replace `mkdirSync` with mkdir from `fs/promises`, it is always better to treat async operation as async processes.

File: packages/beagle-react/cli/init/index.js [hunk 4]
```diff
@@ -17,17 +11,29 @@ if (!fs.existsSync(dir)) {
...
       process.exit()
+    } catch (error) {
+      console.error(error)
+      process.exit(1)
     }
-  })
+  }
+  if (!fs.existsSync(`${dir}/app.tsx`)) {
+    createAppTsx(dir, appContent)
+  }
```
Comment (arthurbleilzup) [inline packages/beagle-react/cli/init/index.js:28]: So, in this peace of code, I see that you are using `fs.existsSync`, but this method is deprecated, see here: [fs.exists is deprecated](https://github.com/verdaccio/monorepo/issues/60). 

So the new method that I suggest to use is `access`, which exists inside `fs/promises`. The implementation of `access`, does not return a `boolean`, if the path or the file does not exists, it rejects the `Promise`, as we are using `async/await`, this method should be inside a `try/catch` block, because when the `Promise.reject()` is called, it will be catched by the `catch` statement, if it exists, the rest of the code inside the `try` statement will be executed normally, so that's why we `return true || return false` that is the same as `Promise.resolve(true) || Promise.resolve(false)`. If you want to reject the promise, you can simply `throw new Error('My error message')`, that is the same as `Promise.reject(new Error('My error message'))`.

Now, considering that you used the destructuring above, here is my suggestion how it would be nice to be implemented:

```suggestion
  const appTsxExists = async (path) => {
     try {
       await access(`${path}/app.tsx`, constants.F_OK)
       return true
     } catch (error) {
       logger.error(error)
       return false
     }
  }

  const appFileExists = await appTsxExists(dir)
  if (!appFileExists) {
    createAppTsx(dir, appContent)
  }
```

**Review by arthurbleilzup — CHANGES_REQUESTED** [review]

**Review by Tiagoperes — DISMISSED** [review]
Just check Arthur's comments pls

**Review by Tiagoperes — APPROVED** [review]

**Review by arthurbleilzup — APPROVED** [review]
